language: node_js
node_js: node
addons:
  firefox: latest
  postgresql: "9.4"
install:
  - npm install
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
before_deploy:
  - 'git config --global user.email "jan@bitovi.com"'
  - 'git config --global user.name "bitballs deploy bot"'
  - node public/build
  - git add public/dist/ --force
  - 'git commit -m "Updating build."'
  - node_modules/.bin/deploy
deploy:
  skip_cleanup: true
  provider: heroku
  app: bitballs
  api_key:
    - secure: dxex208EVkI/C0AURYuCCxvJShEBdQkBy+uQGxkKlZ0QeHwRrjI4zJkgd2DpXW4CjTVCx5GDm20nW5q1ifglLAwWe6MuBVk3tUog33cMHSRaXlbe6jok44XrELPasGw5Rs/WtBzzUcivbpjFFbZtsjaYNMfN7Z3hXZwrUYJTe3sxnH8Dj+Jh059sjghZ5ldCPADiERI4vaN3BT9Ik2WmnsP1WoVzvV5Ohls50VtmG8ntuUmvofWdmXU5S0IeoeczCCEYOc/6s5PtPrITctxIJ5DKLP1CX7AsEZjh2/2QniCW+/5h5G6OfsoJ1P1XkQ2bfxX2V7bVclFEUwHIJMjmLIyXeU9dLPjLfD476nUpfKonAl1TzRW7dTtD0bX+ZbcTXensGqbwGLE5xE2sCnMMqtDPDRhK5MchOJ8q2Jw7YTGj5Hy1OaK+hcHJXTHBSyWS/5NovrqSz3RWCUnVb25nw2h9R3vpiO2rWJtM8L0YTnR0+WWz6RJNEH07m0yD+tPaUJ0PbLwPT5xqKB7QylDYX9zyK9HgpIv7Qub3T36Cz73tqXXbF0Y0w/NH0AWW2lGj4WcBHgh1KG0BOUdpY1M8xmEPGB9EYzttdoLzUBcN1j5JJaiXfZQMcyrvrqoJaRq5JWwB7GeToyPxhZS09FDhdhACqsdVh+o4Eh6Rp9ox8n8=
env:
  global:
    - secure: fdtx+wbZsS/eziFDpe0f7OH5xqtTDZsBMddHQmMsFWX3gNsZPyMJk88/zAoAmk2DPiKxKVdCW6ea+zcbD0ugy4SdILWi3rvRtps05Fd+6UXRKC1ZMBpOAV8hzEWiEAUNSBG5vGH5wvptAGXL00yIVFrXx1v2UZVKtxCEAr51JwTXnoyos8i7g0IsN+gs8dGDiFcUpxA5yKwrKwIhbyDa//y4BxEUNhA4w9kamJIreaWuX+31koCTcPP6khb+wsLbRiUlAlC67fFXpmC6mSAnAN19rKrHpQbVF0/BAbSheJwG5F4T4x4Pfz+FhZDvZA5ZhbIkTDxkX3UaBMEodXFlLQ3wYvnaSvFLNR2/yyQEf+cyPYE5PXgZPm4i9hbBDDUq3BlkSzLMSFo9qQJHI8o0FXvKcO5Xa4r3ckl2tCoW0/nxo5tus20VRVYbadVOwJSS3uh/+VcHAG1wYA4be7RIxr1UBVfV2P5vyBhFMAjrwTLkHLaSnonhU7+ESUhrAwyG5pd1W38Mo7TChKAtOyuG5bL9oKO8zZqwnKGgpmpivkVvdEhCIa5I9RhBvo/D0k3cft0pDs61W8EM0jGWM9Jr8+O6V0nm9qNabEYoYjWakdsPhBAjo8+rKA6+/yxRmA+eztWbNp4N1i1IaxtRJhChN81mCvXl4SLmaP9fICP6wjg=
