language: node_js
node_js: node
addons:
  firefox: latest
  postgresql: '9.4'
install:
  - npm install
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - "psql -c 'create database bitballs;' -U postgres"
before_deploy:
  - 'git config --global user.email "jan@bitovi.com"'
  - 'git config --global user.name "bitballs deploy bot"'
  - node public/build
  - git add public/dist/ --force
  - 'git commit -m "Updating build."'
  - donejs deploy
deploy:
  skip_cleanup: true
  provider: heroku
  app: bitballs
  api_key:
    - secure: dxex208EVkI/C0AURYuCCxvJShEBdQkBy+uQGxkKlZ0QeHwRrjI4zJkgd2DpXW4CjTVCx5GDm20nW5q1ifglLAwWe6MuBVk3tUog33cMHSRaXlbe6jok44XrELPasGw5Rs/WtBzzUcivbpjFFbZtsjaYNMfN7Z3hXZwrUYJTe3sxnH8Dj+Jh059sjghZ5ldCPADiERI4vaN3BT9Ik2WmnsP1WoVzvV5Ohls50VtmG8ntuUmvofWdmXU5S0IeoeczCCEYOc/6s5PtPrITctxIJ5DKLP1CX7AsEZjh2/2QniCW+/5h5G6OfsoJ1P1XkQ2bfxX2V7bVclFEUwHIJMjmLIyXeU9dLPjLfD476nUpfKonAl1TzRW7dTtD0bX+ZbcTXensGqbwGLE5xE2sCnMMqtDPDRhK5MchOJ8q2Jw7YTGj5Hy1OaK+hcHJXTHBSyWS/5NovrqSz3RWCUnVb25nw2h9R3vpiO2rWJtM8L0YTnR0+WWz6RJNEH07m0yD+tPaUJ0PbLwPT5xqKB7QylDYX9zyK9HgpIv7Qub3T36Cz73tqXXbF0Y0w/NH0AWW2lGj4WcBHgh1KG0BOUdpY1M8xmEPGB9EYzttdoLzUBcN1j5JJaiXfZQMcyrvrqoJaRq5JWwB7GeToyPxhZS09FDhdhACqsdVh+o4Eh6Rp9ox8n8=
env:
  global:
    - secure: FN5HgPAyiiw0ySGVJBZefRqJ7cBKWdySkAvyDPwa1mFCiL8wTqBpWcui3O3Gh43NtNkZs7IMna54PFc1SrtEJwzZYDwMt+ukY2+yji5wiDoi3AlPvhXEA2RenDyoOIB+WusD79gXu4jj1i63yc4AV5UGdeEz7Xe3lhfPS2ujejnshNwMT/qFUBhb0pSDEgedLeMFNV/+WxutRLLrSbF+iWy+PxkGjJNMfFQXUO3xwuK4QA+90Mmx70wt1xYwdwkta0Y0fV/+r02IKRgJ/AGJYjnZYhvDIbwpUE9FHu64+tiqNw6W5PcJoCFr4UOSUkRuSStJNn4VQoZzZ+87ji7cIkqUPyA1iQ3RNTjAjnqtSVyVywPTJJjGHHyWr5uD6PiCTxIN7cs55HCFu7Fa/DTfTuleP4VU8IGhq/gQ9g4ACZ+bGqp8Rh7ttFKv4hI88r4OulADzskvRigS7t4gQIBhBmocDu7fGvBZDGq842JQywK9CLSie4Z9suTOBYZpi4KaJ4Lla3fTS0hu1DDlnUxpQde+GOKetfaNmVhvRwZWhmxsxbu5JWvwe+/3YDIFF90mn0Vk6WFPHzq5iZ0UnZw+bjpwRM1ag4TC+4zDiyYsCPcjq9mlseO3bWPDTuOxf0JVoCEu2k0GZkBQChMLuELWxAUcph84fk2NLVdravJkbIw=
